apiVersion: v1
kind: Service
metadata:
  name: word2animal
  labels:
    app: word2animal
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    - port: 50052
      targetPort: 50052
      protocol: TCP
      name: health
  selector:
    app: word2animal
